services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_container
    command: >
      bash -c "python manage.py migrate &&
               python manage.py create_company && 
               python manage.py runserver 0.0.0.0:8001"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      COMPANY_NAME: ${COMPANY_NAME}
      COMPANY_API_TOKEN: ${COMPANY_API_TOKEN}
      ZAPSIGN_URL: ${ZAPSIGN_URL}
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  postgres_data:
