# Generated by Django 5.1.3 on 2024-12-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
